### ISSUE TITLE
[Discuss] should we have a extra list about big&active group

### ISSUE THREAD

**Issue by zclllyybb** [acmerindex/acmer-info#112]
maybe we can introduce an list on groups page with that big group (maybe over 1000 people in it). such a group is usually about some generalized topic and more often active as an hub group but not specific usage. It will help newbie to get more information which is important for their own professional growth.

**Comment by zclllyybb** [comment]
cc @ReiAccept @1804040636

**Comment by ReiAccept** [comment]
Good idea
