### ISSUE TITLE
[新群]: Acmer 炼丹群

### ISSUE THREAD

**Issue by CalcuLuUus** [acmerindex/acmer-info#115]
### 类别

奇怪の群

### 群名

Acmer 炼丹群

### 群号

578177908

### 负责人

竭泽 1046352980

### 描述

本群初衷是建立acmer 深度学习（特别是cv/nlp，当然也可以是其他领域）交流群，可以是分享最新的文献，讨论最新的热点，可以找到相同领域伙伴一起交流，或者分享如何入门深度学习，也欢迎萌新进群，在群里寻求帮助，请教前人学习经验，大家一起讨论。
（应该算是知识学习群

**Comment by zclllyybb** [comment]
搞定了。加入了知识学习相关群序列。
