### ISSUE TITLE
[新群]: 算法竞赛命题人交流群 Polygon Fans

### ISSUE THREAD

**Issue by Zaoly** [acmerindex/acmer-info#152]
### 类别

比赛类

### 群名

Polygon Fans

### 群号

955948515

### 负责人

Zaoly

### 描述

程序设计竞赛（算法竞赛）的顺利举行，离不开命题人的努力。本群是由算法命题爱好者组成的线上交流群，需正确回答问题方可进入。（不是 Polygon 官方群！）

![Polygon Fans](https://github.com/user-attachments/assets/a715b25f-b6e5-4e6c-846f-93bfc218fa07)

**Comment by 1804040636** [comment]
已加
