### ISSUE TITLE
跑团群搜不到捏

### ISSUE THREAD

**Issue by Sola1Go** [acmerindex/acmer-info#62]
奇怪的群 -- acm跑团群 -- 774237545

**Comment by 1804040636** [comment]
> 奇怪的群 -- acm跑团群 -- 774237545
![$H(31UYHDY8F~3$L97S)WTX_tmb](https://user-images.githubusercontent.com/64389500/229290622-423a4151-c1df-4429-96a7-c5b0800b99ee.png)
